# CI/CD workflow for https://github.com/rbk6/website
name: deploy website

on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          repository: rbk6/website
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: master

      - name: build docker image
        id: build
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "building docker image for commit $COMMIT_SHA..."
          docker build -t website:$COMMIT_SHA --target build . || exit 1
          echo "docker image built successfully."

      # todo: add tests step

      - name: ssh to vps and deploy with rsync + docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "syncing with the VPS..."
            mkdir -p ~/.ssh
            echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/deploy-website/

            cd ~/deploy-website
            echo "building docker image locally..."
            docker build -t website:${{ env.COMMIT_SHA }} --target build . || exit 1

            echo "updating docker-compose with the new image..."
            sed -i 's|image: .*$|image: website:${{ env.COMMIT_SHA }}|' docker-compose.yaml

            echo "restarting the service..."
            docker-compose down --volumes --remove-orphans
            docker-compose up -d --build --pull always

            echo "cleaning up unused docker resources..."
            docker image prune -f
