# CI/CD workflow for https://github.com/rbk6/website
name: deploy website

on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          repository: rbk6/website
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: master

      - name: build docker image (without copying to apache dir)
        id: build
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          docker build -t website:$COMMIT_SHA --target build . || exit 1

      # todo: add tests step

      - name: push image to docker hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag website:$COMMIT_SHA ${{ secrets.DOCKER_USERNAME }}/website:$COMMIT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/website:${{ env.COMMIT_SHA }}

      - name: ssh to vps and deploy image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            export DOC_ROOT=${{ secrets.DOC_ROOT }}
            echo "pulling the latest docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/website:${{ env.COMMIT_SHA }}
            echo "building and running the container..."
            docker build --target production -t website:${{ env.COMMIT_SHA }} .
            sudo rm -rf $DOC_ROOT/*
            echo "copying to $DOC_ROOT"
            docker run --rm --name website-container website:${{ env.COMMIT_SHA }} sleep infinity
            docker cp website-container:/website/dist/. $DOC_ROOT/
            docker system prune -f

      - name: cleanup
        run: |
          docker system prune -f
